// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// @ts-ignore Prisma exposes this path at runtime, but the local type package is missing.
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: "file:./dev.db",
  },
});
